/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CaughtUpRouteImport } from './routes/caught-up'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ScanErrorRouteImport } from './routes/scan-error'
import { Route as ScanningRouteImport } from './routes/scanning'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TaskRouteImport } from './routes/task'
import { Route as TodayRouteImport } from './routes/today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaughtUpRoute = CaughtUpRouteImport.update({
  id: '/caught-up',
  path: '/caught-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanErrorRoute = ScanErrorRouteImport.update({
  id: '/scan-error',
  path: '/scan-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanningRoute = ScanningRouteImport.update({
  id: '/scanning',
  path: '/scanning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/caught-up': typeof CaughtUpRoute
  '/completed': typeof CompletedRoute
  '/connect': typeof ConnectRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scan-error': typeof ScanErrorRoute
  '/scanning': typeof ScanningRoute
  '/settings': typeof SettingsRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/caught-up': typeof CaughtUpRoute
  '/completed': typeof CompletedRoute
  '/connect': typeof ConnectRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scan-error': typeof ScanErrorRoute
  '/scanning': typeof ScanningRoute
  '/settings': typeof SettingsRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/caught-up': typeof CaughtUpRoute
  '/completed': typeof CompletedRoute
  '/connect': typeof ConnectRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scan-error': typeof ScanErrorRoute
  '/scanning': typeof ScanningRoute
  '/settings': typeof SettingsRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/caught-up'
    | '/completed'
    | '/connect'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/scan-error'
    | '/scanning'
    | '/settings'
    | '/task'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/caught-up'
    | '/completed'
    | '/connect'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/scan-error'
    | '/scanning'
    | '/settings'
    | '/task'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/caught-up'
    | '/completed'
    | '/connect'
    | '/inbox'
    | '/login'
    | '/notifications'
    | '/scan-error'
    | '/scanning'
    | '/settings'
    | '/task'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CaughtUpRoute: typeof CaughtUpRoute
  CompletedRoute: typeof CompletedRoute
  ConnectRoute: typeof ConnectRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ScanErrorRoute: typeof ScanErrorRoute
  ScanningRoute: typeof ScanningRoute
  SettingsRoute: typeof SettingsRoute
  TaskRoute: typeof TaskRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caught-up': {
      id: '/caught-up'
      path: '/caught-up'
      fullPath: '/caught-up'
      preLoaderRoute: typeof CaughtUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-error': {
      id: '/scan-error'
      path: '/scan-error'
      fullPath: '/scan-error'
      preLoaderRoute: typeof ScanErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanning': {
      id: '/scanning'
      path: '/scanning'
      fullPath: '/scanning'
      preLoaderRoute: typeof ScanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CaughtUpRoute: CaughtUpRoute,
  CompletedRoute: CompletedRoute,
  ConnectRoute: ConnectRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ScanErrorRoute: ScanErrorRoute,
  ScanningRoute: ScanningRoute,
  SettingsRoute: SettingsRoute,
  TaskRoute: TaskRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
